export interface TarotCard {
  id: string;
  name: string;
  slug: string;
  image: string;
  keywords: string[];
  description: string;
  upright: string;
  reversed: string;
  archetype: string;
  element: string;
  astrology?: string;
  // New enriched fields
  meaningLove: string;
  meaningCareer: string;
  meaningFinance: string;
  yesNo: "Yes" | "No" | "Maybe";
  numerology: string;
}

export const majorArcana: TarotCard[] = [
  {
    id: "0",
    name: "The Fool",
    slug: "the-fool",
    image: "/images/tarot/the_fool.webp",
    keywords: ["New Beginnings", "Innocence", "Spontaneity", "Free Spirit", "Leap of Faith"],
    description: "The Fool represents the start of a journey, stepping into the unknown with faith and optimism. It signifies unlimited potential and the need to trust the universe.",
    upright: "A time for new beginnings and adventures. Trust your instincts and take a leap of faith. Embrace the unknown with an open heart.",
    reversed: "Recklessness or naivety. Be careful not to take unnecessary risks without considering the consequences. You may be holding back due to fear.",
    archetype: "The Divine Child",
    element: "Air",
    astrology: "Uranus",
    meaningLove: "In love, The Fool indicates a new, exciting romance or a fresh start in an existing relationship. It encourages you to take a chance on love without fear of rejection. Be open to spontaneous dates and fun adventures.",
    meaningCareer: "A perfect time for a new job, starting a business, or a career pivot. You might feel unready, but your potential is limitless. Trust your creative instincts and innovation.",
    meaningFinance: "Financial opportunities may appear unexpectedly. However, be mindful of impulsive spending. It suggests a time to trust that the universe will provide, but not to be foolish with resources.",
    yesNo: "Yes",
    numerology: "0 (The Void / Infinite Potential)"
  },
  {
    id: "1",
    name: "The Magician",
    slug: "the-magician",
    image: "/images/tarot/the_magician.webp",
    keywords: ["Manifestation", "Resourcefulness", "Power", "Inspired Action", "Skill"],
    description: "The Magician is the bridge between the spiritual and the physical. He reminds you that you have all the tools necessary to succeed.",
    upright: "You have the power to manifest your desires. Use your skills and resources to make things happen. It is a time of action and creation.",
    reversed: "Manipulation or poor planning. You may be misusing your power or talents. Watch out for illusions and deception.",
    archetype: "The Alchemist",
    element: "Air",
    astrology: "Mercury",
    meaningLove: "You have the power to attract the love you desire. If you're single, take action to meet people. In relationships, communication and 'magic' are strong. You can manifest a deeper connection.",
    meaningCareer: "You are in a powerful position to influence your career path. Use your specific skills and determination to seal the deal, get the promotion, or launch the project.",
    meaningFinance: "Great potential for financial gain through your own efforts and skills. Trust in your ability to generate wealth. It's a time to be resourceful.",
    yesNo: "Yes",
    numerology: "1 (New Beginnings, Individuality)"
  },
  {
    id: "2",
    name: "The High Priestess",
    slug: "the-high-priestess",
    image: "/images/tarot/the_high_priestess.webp",
    keywords: ["Intuition", "Sacred Knowledge", "Divine Feminine", "Subconscious", "Mystery"],
    description: "The High Priestess sits at the gate of the great mystery. She represents intuition, wisdom, and the knowledge that comes from within.",
    upright: "Trust your intuition and inner voice. Look beyond the surface to find the truth. It is a time for stillness and reflection.",
    reversed: "Secrets, repressed feelings, or withdrawal. You may be ignoring your intuition or blocking your inner wisdom.",
    archetype: "The Wise Woman",
    element: "Water",
    astrology: "Moon",
    meaningLove: "Love may be mysterious or quiet right now. Trust your gut feelings about a partner. It can also indicate a deep, soulful, almost telepathic connection with someone.",
    meaningCareer: "Trust your instincts regarding business deals or career moves. Not everything is as it seems on the surface. Keep your plans to yourself for now.",
    meaningFinance: "Trust your intuition with money. It's not a time for bold, risky investments but rather for conservative, informed decisions based on 'gut feeling'.",
    yesNo: "Maybe",
    numerology: "2 (Duality, Balance)"
  },
  {
    id: "3",
    name: "The Empress",
    slug: "the-empress",
    image: "/images/tarot/the_empress.webp",
    keywords: ["Fertility", "Femininity", "Beauty", "Nature", "Abundance", "Nurturing"],
    description: "The Empress is the mother of the tarot, representing creation, nurturing, and abundance. She encourages you to connect with nature and your senses.",
    upright: "Creativity and abundance are flowing. Nurture your ideas and relationships. Connect with the beauty around you.",
    reversed: "Creative block or dependence. You may be smothering others or neglecting your own needs. Reconnect with nature to find balance.",
    archetype: "The Great Mother",
    element: "Earth",
    astrology: "Venus",
    meaningLove: "A period of sensuality, beauty, and nurturing in relationships. Deep emotional connection and care. Could also indicate pregnancy or birth of a new phase in love.",
    meaningCareer: "Your creative projects will thrive. It's a great time for artists or anyone needing to 'birth' a new idea. The office environment should be harmonious.",
    meaningFinance: "Abundance is coming your way. It's a good time to invest in your home or comfort. Share your wealth with those you love.",
    yesNo: "Yes",
    numerology: "3 (Creation, Expression)"
  },
  {
    id: "4",
    name: "The Emperor",
    slug: "the-emperor",
    image: "/images/tarot/the_emperor.webp",
    keywords: ["Authority", "Structure", "Control", "Fatherhood", "Discipline"],
    description: "The Emperor represents structure, order, and authority. He reminds you of the importance of logic and discipline in achieving your goals.",
    upright: "Establish order and structure in your life. Take charge of the situation. Logic and reason will guide you to success.",
    reversed: "Domination, rigidity, or lack of discipline. You may be too controlling or, conversely, lacking in leadership.",
    archetype: "The Father",
    element: "Fire",
    astrology: "Aries",
    meaningLove: "A relationship built on a solid foundation, structure, and possibly traditional roles. It can indicate a partner who is protective and stable, though perhaps not overly emotional.",
    meaningCareer: "Take a leadership role. Organization, discipline, and logical planning are key to your success now. Don't be afraid to assert your authority.",
    meaningFinance: "Be disciplined with your budget. Structure your finances and investments logically. Stick to the plan and avoid risky gambling.",
    yesNo: "Yes",
    numerology: "4 (Stability, Structure)"
  },
  {
    id: "5",
    name: "The Hierophant",
    slug: "the-hierophant",
    image: "/images/tarot/the_hierophant.webp",
    keywords: ["Spiritual Wisdom", "Tradition", "Conformity", "Institutions", "Education"],
    description: "The Hierophant represents spiritual authority and tradition. He guides you towards established beliefs and structures.",
    upright: "Seek knowledge from established traditions or mentors. Stick to the rules and follow the conventional path for now.",
    reversed: "Rebellion, personal beliefs, or freedom. You may be challenging the status quo or finding your own spiritual path.",
    archetype: "The Saint / The Teacher",
    element: "Earth",
    astrology: "Taurus",
    meaningLove: "Traditional relationships, marriage, or commitment. Doing things the 'right' way. Shared values and beliefs are crucial for the relationship's success.",
    meaningCareer: "Follow established procedures. It's a good time for education, mentorship, or working within large, traditional organizations. Don't rock the boat.",
    meaningFinance: "Stick to traditional, low-risk investments. Conservative financial management is advised. Seek advice from financial experts.",
    yesNo: "Maybe",
    numerology: "5 (Change, Instability - here bridged by tradition)"
  },
  {
    id: "6",
    name: "The Lovers",
    slug: "the-lovers",
    image: "/images/tarot/the_lovers.webp",
    keywords: ["Love", "Harmony", "Relationships", "Values Alignment", "Choices"],
    description: "The Lovers represent union, harmony, and choices. It signifies a deep connection and the need to align your actions with your values.",
    upright: "Deep connection and harmony in relationships. You are facing an important choice. Choose with your heart and values.",
    reversed: "Disharmony, imbalance, or misalignment of values. You may be facing relationship troubles or making choices out of fear.",
    archetype: "The Union",
    element: "Air",
    astrology: "Gemini",
    meaningLove: "A major soulmate connection. Intense attraction and harmony. However, it also brings a choice: are you ready to commit fully to this person or path?",
    meaningCareer: "Partnerships in business are highlighted. You may need to make a choice between two career paths. ensure your work aligns with your personal values.",
    meaningFinance: "Financial decisions involving a partner. You may need to choose between short-term gain and long-term value alignment.",
    yesNo: "Yes",
    numerology: "6 (Harmony, Communication)"
  },
  {
    id: "7",
    name: "The Chariot",
    slug: "the-chariot",
    image: "/images/tarot/the_chariot.webp",
    keywords: ["Control", "Willpower", "Success", "Action", "Determination"],
    description: "The Chariot represents overcoming obstacles through determination and willpower. It is a sign of victory through discipline.",
    upright: "Success through hard work and determination. Focus your energy and move forward with confidence. You are in the driver's seat.",
    reversed: "Lack of control or direction. You may be feeling aggressive or losing your way. Reassess your goals and regain control.",
    archetype: "The Warrior",
    element: "Water",
    astrology: "Cancer",
    meaningLove: "Pursuing love with determination. You know what you want and you're going for it. However, ensure you aren't 'steamrolling' your partner's feelings.",
    meaningCareer: "Victory is yours if you stay focused. You are moving up quickly. Ambition and drive will conquer any workplace obstacles.",
    meaningFinance: "Take control of your finances. aggressive paying down of debt or saving for a goal (like a car or trip) will be successful.",
    yesNo: "Yes",
    numerology: "7 (Spirituality, Introspection)"
  },
  {
    id: "8",
    name: "Strength",
    slug: "strength",
    image: "/images/tarot/strength.webp",
    keywords: ["Strength", "Courage", "Persuasion", "Influence", "Compassion"],
    description: "Strength represents inner fortitude and the power of the human spirit. It reminds you that true strength comes from compassion and self-control.",
    upright: "You have the inner strength to overcome any challenge. Approach the situation with compassion and patience. Master your emotions.",
    reversed: "Self-doubt, weakness, or insecurity. You may be letting fear hold you back. Reconnect with your inner power.",
    archetype: "The Heroine",
    element: "Fire",
    astrology: "Leo",
    meaningLove: "A passionate, strong bond. It calls for patience and compassion with your partner. Taming the 'beast' within the relationship through gentle understanding.",
    meaningCareer: "You have the endurance to see projects through. Use soft power and persuasion rather than force to get your way in the workplace.",
    meaningFinance: "Avoid impulse buys. Have the strength to stick to your budget even when tempted. Long-term financial stability requires discipline.",
    yesNo: "Yes",
    numerology: "8 (Power, Abundance)"
  },
  {
    id: "9",
    name: "The Hermit",
    slug: "the-hermit",
    image: "/images/tarot/the_hermit.webp",
    keywords: ["Soul Searching", "Introspection", "Being Alone", "Inner Guidance", "Solitude"],
    description: "The Hermit represents a time of introspection and solitude. He encourages you to look within for answers and seek your own truth.",
    upright: "Take time for yourself to reflect and recharge. Seek answers within. Withdrawal from the world can be healing.",
    reversed: "Isolation, loneliness, or withdrawal. You may be cutting yourself off from others too much. Return to the world when ready.",
    archetype: "The Sage",
    element: "Earth",
    astrology: "Virgo",
    meaningLove: "A time to be alone to understand what you truly want in love. If in a relationship, you may need some space or 'me time'.",
    meaningCareer: "You may be rethinking your career path. It's a time for research and deep thought, not necessarily outward action.",
    meaningFinance: "Be prudent and conservative. Step back to analyze your financial situation deeply before making any moves.",
    yesNo: "Maybe",
    numerology: "9 (Completion, Wisdom)"
  },
  {
    id: "10",
    name: "Wheel of Fortune",
    slug: "wheel-of-fortune",
    image: "/images/tarot/wheel_of_fortune.webp",
    keywords: ["Good Luck", "Karma", "Life Cycles", "Destiny", "Turning Point"],
    description: "The Wheel of Fortune represents the cycles of life and the hand of fate. It reminds you that change is inevitable and to go with the flow.",
    upright: "Good luck and positive change are coming. Embrace the cycles of life. Karma is at work.",
    reversed: "Bad luck or resistance to change. You may feel like things are out of your control. Accept that change is a natural part of life.",
    archetype: "Fate",
    element: "Fire",
    astrology: "Jupiter",
    meaningLove: "Fate is at play. You may meet someone by chance, or your relationship is entering a new phase. Go with the flow of events.",
    meaningCareer: "Unexpected opportunities or changes in your job. Luck is on your side, so take a chance. The wheel is turning in your favor.",
    meaningFinance: "Fluctuations in finances are likely. If you've been down, you're coming up. If you're up, save for a rainy day.",
    yesNo: "Yes",
    numerology: "10 (1+0=1: New Cycle)"
  },
  {
    id: "11",
    name: "Justice",
    slug: "justice",
    image: "/images/tarot/justice.webp",
    keywords: ["Justice", "Fairness", "Truth", "Cause and Effect", "Law"],
    description: "Justice represents fairness, truth, and the law. It reminds you that your actions have consequences and to always seek the truth.",
    upright: "Justice will be served. Act with integrity and fairness. The truth will come to light.",
    reversed: "Unfairness, dishonesty, or lack of accountability. You may be avoiding the truth or facing an unjust situation.",
    archetype: "The Judge",
    element: "Air",
    astrology: "Libra",
    meaningLove: "Fairness and equality in relationships. If you've been treating your partner well, you will be rewarded. Legal matters regarding marriage/divorce.",
    meaningCareer: "Workplace disputes will be settled fairly. Contracts and legal documents are highlighted. Ensure all your dealings are above board.",
    meaningFinance: "Balance your books. If you are owed money, it may come. If you owe money, pay it. Financial karma is active.",
    yesNo: "Maybe",
    numerology: "11 (Master Number: Intuition)"
  },
  {
    id: "12",
    name: "The Hanged Man",
    slug: "the-hanged-man",
    image: "/images/tarot/the_hanged_man.webp",
    keywords: ["Pause", "Surrender", "Letting Go", "New Perspective", "Sacrifice"],
    description: "The Hanged Man represents a time of suspension and waiting. He encourages you to look at things from a different perspective and let go of control.",
    upright: "Pause and reflect. Let go of the need to control. A shift in perspective is needed.",
    reversed: "Delays, resistance, or stalling. You may be holding onto something that no longer serves you. It's time to make a sacrifice.",
    archetype: "The Martyr / The Mystic",
    element: "Water",
    astrology: "Neptune",
    meaningLove: "A pause in the relationship. It's not the time to push for action. Let go and see things from your partner's point of view.",
    meaningCareer: "Projects may be stalled. Don't force it. Use this time to rethink your strategy or learn a new skill.",
    meaningFinance: "Money might be tight or delayed. A sacrifice now (saving) will lead to gain later. Change your perspective on wealth.",
    yesNo: "Maybe",
    numerology: "12 (1+2=3: Creation suspended)"
  },
  {
    id: "13",
    name: "Death",
    slug: "death",
    image: "/images/tarot/death.webp",
    keywords: ["Endings", "Change", "Transformation", "Transition", "Rebirth"],
    description: "Death represents the end of a cycle and the beginning of a new one. It signifies transformation and the need to let go of the past.",
    upright: "A major transformation is occurring. Let go of what no longer serves you to make room for the new. Embrace change.",
    reversed: "Resistance to change or inability to move on. You may be holding onto the past out of fear. Accept the inevitable.",
    archetype: "Rebirth",
    element: "Water",
    astrology: "Scorpio",
    meaningLove: "A relationship may be ending or changing significantly. It's necessary for growth. If single, you must kill off old habits to find love.",
    meaningCareer: "A job or career path is coming to an end. Don't cling to it. A new, better opportunity is waiting to be born.",
    meaningFinance: "A financial loss or change in income source. It's a time to restructure your finances completely.",
    yesNo: "No",
    numerology: "13 (Karmic Number: Upheaval)"
  },
  {
    id: "14",
    name: "Temperance",
    slug: "temperance",
    image: "/images/tarot/temperance.webp",
    keywords: ["Balance", "Moderation", "Patience", "Purpose", "Alchemy"],
    description: "Temperance represents balance, moderation, and patience. It reminds you to find the middle ground and integrate opposites.",
    upright: "Find balance and moderation in your life. Have patience and trust the process. Integration leads to harmony.",
    reversed: "Imbalance, excess, or lack of long-term vision. You may be acting impulsively or out of alignment. Restore harmony.",
    archetype: "The Healer",
    element: "Fire",
    astrology: "Sagittarius",
    meaningLove: "A balanced, harmonious relationship. Patience is key. You and your partner are learning to blend your lives together smoothly.",
    meaningCareer: "Set long-term goals. Avoid taking risks. Cooperation and compromise in the workplace will bring success.",
    meaningFinance: "Balance your budget. Save a little, spend a little. Avoid extremes in financial management.",
    yesNo: "Yes",
    numerology: "14 (1+4=5: Change through balance)"
  },
  {
    id: "15",
    name: "The Devil",
    slug: "the-devil",
    image: "/images/tarot/the_devil.webp",
    keywords: ["Shadow Self", "Attachment", "Addiction", "Restriction", "Sexuality", "Materialism"],
    description: "The Devil represents bondage, addiction, and materialism. He reminds you that you have the power to free yourself from your own chains.",
    upright: "You may be feeling trapped or restricted. Examine your attachments and addictions. reclaim your power.",
    reversed: "Breaking free, releasing limiting beliefs, or detachment. You are reclaiming your power and moving towards freedom.",
    archetype: "The Shadow",
    element: "Earth",
    astrology: "Capricorn",
    meaningLove: "Obsession, codependency, or purely lustful connection. It can be intense but potentially toxic. Are you staying out of fear?",
    meaningCareer: "Feeling trapped in a job you hate, perhaps for the money ('golden handcuffs'). Be wary of unethical business practices.",
    meaningFinance: "Obsession with material wealth. You may be spending to fill a void. Debt could become a shackle.",
    yesNo: "No",
    numerology: "15 (1+5=6: Harmony distorted)"
  },
  {
    id: "16",
    name: "The Tower",
    slug: "the-tower",
    image: "/images/tarot/the_tower.webp",
    keywords: ["Sudden Change", "Upheaval", "Chaos", "Revelation", "Awakening", "Disaster"],
    description: "The Tower represents sudden, disruptive change. While it can be destructive, it often clears the way for a necessary rebuilding.",
    upright: "Sudden change or upheaval is coming. Foundations are being shaken. Embrace the chaos as a catalyst for growth.",
    reversed: "Personal transformation, fear of change, or averting disaster. You may be resisting necessary change. Let the tower fall.",
    archetype: "The Liberator",
    element: "Fire",
    astrology: "Mars",
    meaningLove: "A breakup or a massive argument that shakes the foundation of the relationship. The truth comes out. It's painful but necessary.",
    meaningCareer: "Sudden job loss or company collapse. The structure you relied on is gone. It forces you to build something better.",
    meaningFinance: "Unexpected financial crisis. Bankruptcy or major loss. It's a warning to have a safety net.",
    yesNo: "No",
    numerology: "16 (1+6=7: Spiritual challenge)"
  },
  {
    id: "17",
    name: "The Star",
    slug: "the-star",
    image: "/images/tarot/the_star.webp",
    keywords: ["Hope", "Faith", "Purpose", "Renewal", "Spirituality", "Inspiration"],
    description: "The Star represents hope, inspiration, and spiritual renewal. It is a sign that you are on the right path and the universe is supporting you.",
    upright: "Hope and faith are restored. You are feeling inspired and renewed. Trust in the universe.",
    reversed: "Lack of faith, despair, or discouragement. You may be feeling disconnected or uninspired. Reconnect with your hope.",
    archetype: "The Guide",
    element: "Air",
    astrology: "Aquarius",
    meaningLove: "Optimism in love. Healing from past wounds. You are open to love again. A spiritual connection with a partner.",
    meaningCareer: "You are inspired by your work. Great for creative or humanitarian careers. You have a clear vision of your future.",
    meaningFinance: "Financial goals are within reach. Have faith in your plan. Generosity will be rewarded.",
    yesNo: "Yes",
    numerology: "17 (1+7=8: Strength through hope)"
  },
  {
    id: "18",
    name: "The Moon",
    slug: "the-moon",
    image: "/images/tarot/the_moon.webp",
    keywords: ["Illusion", "Fear", "Anxiety", "Subconscious", "Intuition", "Dreams"],
    description: "The Moon represents illusions, fears, and the subconscious. It reminds you that things are not always what they seem and to trust your intuition.",
    upright: "Trust your intuition. Things may be unclear or confusing. Face your fears and explore your subconscious.",
    reversed: "Release of fear, repressed emotion, or confusion. You are gaining clarity and overcoming your anxieties.",
    archetype: "The Dreamer",
    element: "Water",
    astrology: "Pisces",
    meaningLove: "Confusion or deception in relationships. Secrets may be kept. Trust your intuition over what you see on the surface.",
    meaningCareer: "Uncertainty at work. Lack of clear direction. Be careful of misunderstandings or people with hidden agendas.",
    meaningFinance: "Be cautious with investments. You don't have all the facts. Avoid gambling or risky schemes.",
    yesNo: "No",
    numerology: "18 (1+8=9: Completion in darkness)"
  },
  {
    id: "19",
    name: "The Sun",
    slug: "the-sun",
    image: "/images/tarot/the_sun.webp",
    keywords: ["Positivity", "Fun", "Warmth", "Success", "Vitality", "Joy"],
    description: "The Sun represents success, joy, and vitality. It is a sign of abundance and radiance. Everything is coming to light.",
    upright: "Success and happiness are yours. embrace the joy and warmth of the sun. You are radiating positive energy.",
    reversed: "Inner child, feeling down, or overly optimistic. You may be struggling to find the joy. Reconnect with your inner light.",
    archetype: "The Divine Child",
    element: "Fire",
    astrology: "Sun",
    meaningLove: "Joy, happiness, and engagement. A very positive card for relationships. Fun, warmth, and mutual celebration.",
    meaningCareer: "Success, recognition, and promotion. You are shining at work. Your efforts are being noticed and rewarded.",
    meaningFinance: "Abundance and financial growth. Investments pay off. It's a time of prosperity.",
    yesNo: "Yes",
    numerology: "19 (1+9=10=1: New level of success)"
  },
  {
    id: "20",
    name: "Judgement",
    slug: "judgement",
    image: "/images/tarot/judgement.webp",
    keywords: ["Judgement", "Rebirth", "Inner Calling", "Absolution", "Awakening"],
    description: "Judgement represents a time of reckoning and awakening. It calls you to rise up and embrace your higher calling.",
    upright: "A time for reflection and self-evaluation. You are being called to a higher purpose. Rise up and answer the call.",
    reversed: "Self-doubt, refusal of call, or lack of self-awareness. You may be ignoring your inner calling. Listen to your soul.",
    archetype: "The Resurrection",
    element: "Fire",
    astrology: "Pluto",
    meaningLove: "Renewal of a relationship or a decision to move on. A 'wake-up call' in love. Forgiving past mistakes.",
    meaningCareer: "A career calling. You are realizing your true vocation. A major decision point regarding your professional path.",
    meaningFinance: "A judgment call on your finances. If you've been responsible, you'll be fine. If not, it's time to pay the piper.",
    yesNo: "Yes",
    numerology: "20 (2+0=2: Higher balance)"
  },
  {
    id: "21",
    name: "The World",
    slug: "the-world",
    image: "/images/tarot/the_world.webp",
    keywords: ["Completion", "Integration", "Accomplishment", "Travel", "Wholeness"],
    description: "The World represents completion, integration, and accomplishment. It signifies the end of a journey and the beginning of a new one.",
    upright: "Completion of a cycle or goal. You have achieved what you set out to do. Celebrate your success.",
    reversed: "Incompletion, lack of closure, or delays. You may be close to the finish line but facing obstacles. Tie up loose ends.",
    archetype: "The Whole",
    element: "Earth",
    astrology: "Saturn",
    meaningLove: "Fulfillment in love. Marriage, finding 'the one', or completing a major phase together. Could involve travel.",
    meaningCareer: "Reaching the pinnacle of your career. Global opportunities, travel for work, or completing a major project.",
    meaningFinance: "Financial goals reached. Wealth and abundance. You have everything you need.",
    yesNo: "Yes",
    numerology: "21 (2+1=3: Ultimate expression)"
  }
];

export function getTarotCardBySlug(slug: string): TarotCard | undefined {
  return majorArcana.find(card => card.slug === slug);
}

export function getAllTarotCards(): TarotCard[] {
  return majorArcana;
}
