import React from "react";
import { Metadata } from "next";
import { WithContext, FAQPage as FAQPageSchema, BreadcrumbList } from "schema-dts";
import FAQClient from "./client";

export const metadata: Metadata = {
  title: "FAQ - Frequently Asked Questions | Oniromancy AI",
  description: "Find answers to common questions about AI dream interpretation, tarot readings, horoscopes, pricing, and privacy.",
  alternates: {
    canonical: "https://www.oniromancy.com/faq",
  },
  openGraph: {
    title: "FAQ - Frequently Asked Questions | Oniromancy AI",
    description: "Common questions about our AI-powered spiritual tools.",
    url: "https://www.oniromancy.com/faq",
    type: "website",
  },
};

const faqs = [
  {
    category: "General & Philosophy",
    iconName: "HelpCircle",
    questions: [
      {
        q: "What is Oniromancy AI?",
        a: "Oniromancy AI is a digital sanctuary blending ancient divination arts—Dream Interpretation, Tarot, and Astrology—with modern Artificial Intelligence. We provide psychologically grounded insights to help you navigate your subconscious and daily life."
      },
      {
        q: "Is this just for entertainment?",
        a: "While our tools are engaging, they are designed for introspection. We use Jungian psychology and archetypal symbolism to offer meaningful perspectives, acting as a mirror for your inner thoughts rather than a simple magic 8-ball."
      },
      {
        q: "Do I need to be an expert in spirituality?",
        a: "No prior knowledge is required. Our AI explains symbols and meanings in clear, accessible language, making these ancient tools useful for everyone, from beginners to seasoned practitioners."
      }
    ]
  },
  {
    category: "Dream Interpretation",
    iconName: "Brain",
    questions: [
      {
        q: "How accurate is the AI dream interpretation?",
        a: "Our AI is trained on extensive literature regarding dream symbolism (Freud, Jung, and modern psychology). While no interpretation is 'absolute' since dreams are personal, our system identifies universal themes and symbols to provide a highly relevant starting point for your own reflection."
      },
      {
        q: "Can I visualize my dreams?",
        a: "Yes! We use advanced generative AI to recreate scenes from your dreams based on your description. These visuals capture the surreal and emotional essence of your dream world."
      },
      {
        q: "Is my dream journal private?",
        a: "Your privacy is paramount. Your dream entries are encrypted and never shared with third parties or used for advertising. They are strictly for your personal use and analysis."
      }
    ]
  },
  {
    category: "Tarot & Divination",
    iconName: "Sparkles",
    questions: [
      {
        q: "How does digital Tarot work?",
        a: "We simulate the randomness of a physical deck shuffle using cryptographic algorithms. The interpretation is then generated by considering the card's traditional meaning, its position in the spread, and your specific question."
      },
      {
        q: "What Tarot deck do you use?",
        a: "We currently use imagery inspired by the classic Rider-Waite-Smith deck, as it is the most widely recognized standard for symbolism. Our AI is also tuned to interpret these specific archetypes."
      },
      {
        q: "Can I ask the same question twice?",
        a: "You can, but Tarot is most effective when you respect the first answer. Repeatedly asking the same question often leads to confusion. We recommend meditating on the first reading before seeking more clarity."
      }
    ]
  },
  {
    category: "Horoscope & Astrology",
    iconName: "Moon",
    questions: [
      {
        q: "What system of astrology do you use?",
        a: "We use Western Tropical astrology. Our daily horoscopes are calculated based on planetary transits relative to your sun sign, focusing on themes of personal growth and emotional well-being."
      },
      {
        q: "When are daily horoscopes updated?",
        a: "Horoscopes are updated every day at midnight UTC. You can check back daily for new insights tailored to the current celestial climate."
      }
    ]
  },
  {
    category: "Credits & Payments",
    iconName: "CreditCard",
    questions: [
      {
        q: "How does the credit system work?",
        a: "Basic features are free. Advanced tools—like high-res dream visualization or complex multi-card Tarot spreads—require credits. You can purchase credit packs as needed, and they never expire."
      },
      {
        q: "Do you offer refunds?",
        a: "If you encounter a technical error that wasted your credits (e.g., a failed generation), please contact support, and we will happily refund those credits to your account."
      }
    ]
  },
  {
    category: "Technical Support",
    iconName: "Wrench",
    questions: [
      {
        q: "The image generation is slow, why?",
        a: "High-quality AI image generation requires significant computing power. Depending on server load, it may take 10-30 seconds to generate a unique dream visual. We appreciate your patience!"
      },
      {
        q: "How do I report a bug?",
        a: "You can reach out to us via the Contact page or email our support team directly. We appreciate user feedback and strive to fix issues quickly."
      }
    ]
  }
];

export default function FAQPage() {
  const jsonLd: WithContext<FAQPageSchema> = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.flatMap(category => 
      category.questions.map(item => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: {
          "@type": "Answer",
          text: item.a
        }
      }))
    )
  };

  const breadcrumbJsonLd: WithContext<BreadcrumbList> = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: "https://www.oniromancy.com",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "FAQ",
        item: "https://www.oniromancy.com/faq",
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <FAQClient faqs={faqs} />
    </>
  );
}
